### PR TITLE
Remove unused function in 'signed_chart.py'

### PR DESCRIPTION
**Pull request by mgoerens**

### CODE REVIEW

**Comment by komish** [comment]
Instead of removing it because it's unused, should we thinking about where the rest of its related functions are called and look to use it there?

As in, should we extending a workflow to assert what this function intends to assert?

**Comment by komish** [comment]
@mgoerens I don't remember if we've discussed this one yet, so pinging you on this one to see where we landed re: the above comment ^

**Review by komish — APPROVED** [review]
/lgtm

**Comment by mgoerens** [comment]
@komish I think your comment makes sense generally speaking. In that particular case I don't see a use for this function. Also it would need a rewrite.. I would not return `True` if we can't find a key in the owners file..

I will hit the merge button and remove this unused function

**Pull request merged**
