### PR TITLE
Increase timeout of nightly pipeline to 10 hours

### PR DESCRIPTION
**Pull request by mgoerens**

### CODE REVIEW

**Review by komish — APPROVED** [review]
/lgtm

**Review by komish — CHANGES_REQUESTED** [review]
You probably also need this here:

- https://github.com/openshift-helm-charts/development/blob/main/.github/workflows/test.yml
- https://github.com/openshift-helm-charts/development/blob/main/.github/workflows/release.yml

**Comment by mgoerens** [comment]
@komish Good point, done

**Review by komish — APPROVED** [review]
/lgtm

**Pull request merged**
