### PR TITLE
add bot as approver

### PR DESCRIPTION
**Pull request by mmulholla**

### CODE REVIEW

**Comment by mmulholla** [comment]
Get ready for auto-release

**Review by zonggen — APPROVED** [review]

**Comment by zonggen** [comment]
Why do we need it in `development`?

**Comment by mmulholla** [comment]
This is needed. As part of autorelease a PR will be created to add any new charts from the charts repository to teh devlopment repository. This will be submitted by the bot and part of the release checking includes if the submitter is authorized.

**Review by zonggen — APPROVED** [review]

**Pull request merged**
