### PR TITLE
Fix the test failures when running in fork

### PR DESCRIPTION
**Pull request by tisutisu**
It will resolve the test run failures when running in fork with different BOT_NAME as observed in below run.
https://github.com/mmulholla/development/runs/4472014139?check_suite_focus=true#step:7:132

### CODE REVIEW

**Comment by zonggen** [comment]
Change LGTM, I've revert the parallel test feature, please rebase on top of latest main and rerun the tests. As long as the tests all pass, I think we're good to merge.

**Review by mmulholla — APPROVED** [review]
LGTM

**Comment by mmulholla** [comment]
@sushanta please rebase this fix on latest main

**Comment by mmulholla** [comment]
> @sushanta please rebase this fix on latest main

I did the rebase and moved the new @given to conftest.py

**Pull request merged**
