### PR TITLE
search for partners in directory if provider type is partner

### PR DESCRIPTION
**Pull request by Kartikey-star**
This PR updates the getChartUpdate to search for partners if provider type used in segment is partner , so as to match our directory structure.
Signed-off-by: Kartikey-star <41898282+github-actions[bot]@users.noreply.github.com>

### CODE REVIEW

**Review by tisutisu — APPROVED** [review]
LGTM

**Review by tisutisu — CHANGES_REQUESTED** [review]
Have to fix this error `.github/workflows/build.yml (Line: 361, Col: 13): Unexpected symbol: '$GITHUB_REPOSITORY'. Located at position 72 within expression: always() && steps.check_build_required.outputs.run-build == 'true' && ($GITHUB_REPOSITORY == "openshift-helm-charts/charts" || $GITHUB_REPOSITORY == "openshift-helm-charts/development")
`

**Review by mmulholla — APPROVED** [review]
LGTM

**Review by tisutisu — APPROVED** [review]
LGTM

**Pull request merged**
