### PR TITLE
Added sha value mismatch and invalid url test scenarios

### PR DESCRIPTION
**Pull request by tisutisu**
This PR will cover below stories: 
https://issues.redhat.com/browse/HELM-265
https://issues.redhat.com/browse/HELM-280

### CODE REVIEW

**Review by mmulholla — COMMENTED** [review]
I would like to understand if this test could follow a similar pattern to that I used for chart-verifier test. See: https://github.com/redhat-certification/chart-verifier/pull/220

Another alternative is to add a json file for each chart which defines the message it expects. Then provide the location of the json file as a parameter. This way the code can be used for other issues in the report.

**Comment by tisutisu** [comment]
> I would like to understand if this test could follow a similar pattern to that I used for chart-verifier test. See: [redhat-certification/chart-verifier#220](https://github.com/redhat-certification/chart-verifier/pull/220)
> 
> Another alternative is to add a json file for each chart which defines the message it expects. Then provide the location of the json file as a parameter. This way the code can be used for other issues in the report.

Added this change, as discussed.

**Review by mmulholla — APPROVED** [review]
LGTM - nice work!

**Comment by zonggen** [comment]
Change LGTM, please rebase to latest main so that parallel testing has no impact.

**Comment by tisutisu** [comment]
> Change LGTM, please rebase to latest main so that parallel testing has no impact.

rebase to main, now all the test are passing.

**Pull request merged**
